networks:
  devices-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    restart: always
    container_name: devices-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: devices_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devices-network

  api:
    build: .
    container_name: devices-api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: devices-db
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: devices_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    networks:
      - devices-network

volumes:
  pgdata:
