openapi: 3.0.3
info:
  title: 1Devices API
  description: API for managing devices resources
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
paths:
  /devices:
    get:
      summary: Get a list of devices
      operationId: listDevices
      tags:
        - Devices
      responses:
        '200':
          description: A list of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
    post:
      summary: Create a new device
      operationId: createDevice
      tags:
        - Devices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '201':
          description: Device created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '400':
          description: Invalid input
  /devices/{id}:
    get:
      summary: Get a device by ID
      operationId: getDevice
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Device details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found
    put:
      summary: Update a device by ID
      operationId: updateDevice
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '200':
          description: Device updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found
    delete:
      summary: Delete a device by ID
      operationId: deleteDevice
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Device deleted successfully
        '404':
          description: Device not found
components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "cellphone"
        brand:
          type: string
          example: "xPhone"
        state:
          type: string
          example: "available"
        creation time:
          type: string
          format: date-time
          example: "2024-02-2025T12:00:00Z"
